databases:
  - name: production
    databaseName: hannahsblog_db
    user: sethstrouf

services:
  - type: web
    name: webdis
    env: ruby
    region: oregon
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hannahsblog_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
